### ISSUE TITLE
Explain the difference with RQ

### ISSUE THREAD

**Issue by alexgarel** [wakatime/wakaq#1]
I saw wakaq today. I think it's great to have lightweight alternatives to celery which is quite complex and not always easy to setup in a reliable way…

In the README the subtitle makes the difference with celery clear: it's lightweight, but what about a framework like https://python-rq.org/ ?
On a project I was to go for RQ but maybe I would have good reason to try wakaq ?

I opened an issue because I think it's worth mentioning in the README.

**Comment by csangonzo** [comment]
We're currently using rq and I'm always on the look for alternatives, so I'm curious about this too.

**Comment by alanhamlett** [comment]
WakaQ comes with a built-in scheduler, so you can run tasks for ex: once every day or once every week at set times. Run it with `wakaq-scheduler` after `pip install wakaq`.

WakaQ can run tasks at a later time (eta tasks) by giving a timedelta or datetime eta, but RQ can't do that afaik.

WakaQ has queue priorities, so tasks from queue A can be run before tasks from queue B. Even if all total tasks finish around the same time, it matters to prioritize user-blocking tasks before others.

WakaQ can auto-retry tasks, if a task runs into the soft timeout.

**Comment by alexgarel** [comment]
Thanks @alanhamlett for the explanation, and thanks for sharing this project. It's always cool to have new projects :-)

Note that rq scheduler exists but as a side project (https://github.com/rq/rq-scheduler), it gives scheduling and eta tasks.

Also regarding tasks priorities, it's not very explicit in their documentation, but the order in which you pass queues to the worker sets the priority (so priority is more at the worker level) but [you can have a different strategy](https://python-rq.org/docs/workers/#round-robin-and-random-strategies-for-dequeuing-jobs-from-queues)

> WakaQ can auto-retry tasks, if a task runs into the soft timeout.

Is it different from [rq retry](https://python-rq.org/docs/exceptions/#retrying-failed-jobs) ? Do you mean retry in RQ do not handle the case of soft timeout ?

**Comment by alanhamlett** [comment]
Then there doesn't seem to be any feature differences between RQ and WakaQ, just in how those features are implemented.

**Comment by kirubakaran** [comment]
I too use [RQ](https://python-rq.org/) along with [django-rq](https://github.com/rq/django-rq) at [histre](https://histre.com/) and I'd love to know if someone were to do a benchmark or other such comparisons. It would be good to know at what point it would make sense to switch.

**Comment by alanhamlett** [comment]
> I too use [RQ](https://python-rq.org/) along with [django-rq](https://github.com/rq/django-rq) at [histre](https://histre.com/) and I'd love to know if someone were to do a benchmark or other such comparisons. It would be good to know at what point it would make sense to switch.

Looks like RQ [forks a process for every task](https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/worker.py#L774) but that might be configurable, I didn't look very long. If that's the case, it probably has a slightly noticeable slower task throughput than Celery and WakaQ which re-use forked workers for multiple tasks.

If you're not seeing bottlenecks with RQ then isn't it premature optimization?
