### ISSUE TITLE
Asyncio Support

### ISSUE THREAD

**Issue by ethanleifer** [wakatime/wakaq#2]
Does wakaq support async tasks?

**Comment by alanhamlett** [comment]
Dunno, never tried. All my tasks are sync.

**Comment by alanhamlett** [comment]
~~Calling async functions from WakaQ tasks works with this behavior:~~

* ~~if you call `await` the task won't finish until the async function completes~~
* ~~if you don't use `await`, the task will finish and the worker process will consume a new task while still running the async code in the same process~~

~~Task timeouts aren't supported for async code without using `await`.~~

Currently the only way to run async code in a WakaQ task is [converting an async function to sync](https://docs.djangoproject.com/en/5.1/topics/async/#async-to-sync). Running an async function without `await` from non-async code means there's no async event loop and the async function never actually executes.

**Comment by alanhamlett** [comment]
More info in [this stackoverflow](https://stackoverflow.com/questions/39815771/how-to-combine-celery-with-asyncio) about using [asgiref](https://pypi.org/project/asgiref/) to run async functions from synchronous tasks. It's about Celery, but it also applies to WakaQ.

**Comment by alanhamlett** [comment]
Added async task support in v3.0.0.
