### ISSUE TITLE
Trying to run, got AttributeError: 'method-wrapper' object has no attribute 'worker_log_file'

### ISSUE THREAD

**Issue by oiwn** [wakatime/wakaq#5]
Hello. Using provided in README example. Trying to run worker ```wakaq-worker --app=wcheck.__init__```

```
  File "/opt/homebrew/Caskroom/miniforge/base/envs/wcheck/lib/python3.10/site-packages/wakaq/logger.py", line 44, in setup_logging
    log_file = wakaq.scheduler_log_file if is_scheduler else wakaq.worker_log_file
AttributeError: 'method-wrapper' object has no attribute 'worker_log_file'
```

Any hints? I tried to add ```worker_log_file``` into WakaQ instance initialization but still no success.

**Comment by alanhamlett** [comment]
Your app path isn't a `WakaQ` instance. Improved the error message with c4df7eb31a4416edad20bf339c955f59d2c0321e.

**Comment by oiwn** [comment]
oh, thank you, now working!

had to run it like ```wakaq-worker --app=wcheck.wakaq``` where wakaq is instance of WakaQ class.
