### ISSUE TITLE
Redis username, password and database support

### ISSUE THREAD

**Issue by MykalMachon** [wakatime/wakaq#6]
Hi 👋
Is there username, password and database (db) support for the Redis broker right now? 
If not, is this something you'd want to see as a feature? **I'd be willing to submit a PR!** 

## Background on the issue
I'm currently trying to move from Celery to WakaQ due to recurring issues with Celery idling indefinitely while there is a queue of unstarted tasks in Redis. However, our Redis instance is cloud hosted and has a password on it; passing WakaQ the connection string I used with celery (`redis://<my-user>:<my-pass>@<redis-host>:<redis-port>/<redis-db>`) doesn't seem to work so I'm a bit stuck. 

## Possible implementation 
After a quick look through the source, the [Redis package WakaQ is using](https://github.com/redis/redis-py) supports usernames and passwords so it would be as simple as adding a few extra params to [`__init__.WakaQ.__init__()`](https://github.com/wakatime/wakaq/blob/main/wakaq/__init__.py#L50) and dropping in the `username`, `password` and `db` params for the Redis instance if they're not equal to `None`. 

Here's a rough preview of the changes that would need to be done:
```python
   def __init__(
        self,
        queues=[],
        schedules=[],
        host="localhost",
        port=6379,
        username=None,
        password=None,
        db="0" # the default database
        ...
    ):
    ...
    self.broker = redis.Redis(
            host=host,
            port=port,
            username=username,
            password=password,
            db=db,
            charset="utf-8",
            decode_responses=True,
            health_check_interval=health_check_interval,
            socket_timeout=socket_timeout,
            socket_connect_timeout=socket_connect_timeout,
        )


```

BTW, thanks for building WakaQ! I've used WakaTime for a few years, and I'm sure it's tracked a lot of the time I spent fixing bugs in Celery 😅

**Comment by alanhamlett** [comment]
Released in v1.3.0. Let me know how the migration from Celery goes!
